# Generated by Django 3.1.4 on 2021-01-07 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Store',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='creationDate',
            new_name='postDate',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='creationDate',
            new_name='addedDate',
        ),
        migrations.AddField(
            model_name='product',
            name='fromAge',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='Products/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=45),
        ),
        migrations.AddField(
            model_name='product',
            name='mainMaterial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='item.materialscategory'),
            preserve_default=False,
        ),
    ]
