# Generated by Django 3.1.4 on 2021-01-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_languagechar_languagetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='history',
            field=models.TextField(default='qdqd'),
        ),
    ]
