# Generated by Django 3.1.4 on 2021-01-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_product_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='history',
            field=models.TextField(),
        ),
    ]
