# Generated by Django 3.1.4 on 2021-01-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20210110_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_text1', models.CharField(max_length=25)),
                ('menu_text2', models.CharField(max_length=25)),
                ('menu_text3', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='LanguageChar',
        ),
        migrations.DeleteModel(
            name='LanguageText',
        ),
    ]
