# Generated by Django 3.1.4 on 2021-01-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_auto_20210110_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='language1',
            name='category_name',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language1',
            name='category_name2',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language1',
            name='category_name3',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
