# Generated by Django 3.1.4 on 2021-01-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_auto_20210110_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='language1',
            name='category_text',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
    ]
