# Generated by Django 3.1.4 on 2021-01-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_language1_category_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='language1',
            name='signup_text',
            field=models.CharField(default=1, max_length=35),
            preserve_default=False,
        ),
    ]
