# Generated by Django 3.1.4 on 2021-01-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_language1_signup_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='language1',
            name='buy_text',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
