# Generated by Django 3.1.4 on 2021-01-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_language1_login_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='address',
            field=models.CharField(default=1, max_length=65),
            preserve_default=False,
        ),
    ]
