# Generated by Django 3.1.4 on 2021-01-14 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_trade_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='product',
        ),
    ]
